import { QueueStatus, QueuedOperation, TaskUiStatus } from '../types/app';

export const taskStatusLabels: Record<string, string> = {
  not_started: 'Не начато',
  draft: 'Черновик',
  ready_local: 'Готово локально',
  queued: 'В очереди',
  processed: 'Обработано',
};

export const queueStatusLabels: Record<QueueStatus, string> = {
  queued: 'В очереди',
  processing: 'Обрабатывается',
  synced: 'Обработано',
  failed: 'Ошибка',
  waiting_for_auth: 'Ожидает авторизацию',
};

export const queueTypeLabels: Record<QueuedOperation['type'], string> = {
  create_variety: 'Создание сорта',
  write_sheet: 'Запись в локальный шаблон',
  submit_task: 'Сохранение шага',
};

export const v2Copy = {
  appTitle: 'Сортовед Соя',
  loading: 'Загрузка v2...',
  startSubtitle: 'v2: локальные экраны и логика без облачной синхронизации',
  startIntro:
    'Сначала собираем весь пользовательский поток локально: импорт ссылки, создание сорта по шаблону, карточку сорта и все шаги наблюдений.',
  startLink: 'Добавить ссылку',
  startCreate: 'Создать сорт',
  startCatalog: 'Список сортов',
  startQueue: 'Локальная очередь',
  googleDisabled: 'Облачная синхронизация временно отключена',
  back: 'Назад',
  next: 'Далее',
  createVariety: 'Создать сорт',
  errorTitle: 'Ошибка',
  doneTitle: 'Готово',
  authLinkTitle: 'Подключение сорта',
  authCreateTitle: 'Подготовка создания сорта',
  authLinkBody:
    'На этом этапе ссылка будет прочитана из буфера обмена, проверена и добавлена в локальный каталог приложения.',
  authCreateBody:
    'На этом этапе новый сорт создается локально по шаблону, без отправки в Google Sheets.',
  authLinkAction: 'Проверить ссылку из буфера',
  authCreateAction: 'Перейти к мастеру создания',
  catalogTitle: 'Список сортов',
  catalogEmptyTitle: 'Сортов пока нет',
  catalogEmptyBody: 'Подключите существующую таблицу или создайте сорт по локальному шаблону.',
  catalogAdd: 'Добавить сорт',
  varietyIntro:
    'Откройте шаг карточки сорта и заполните локальное наблюдение, измерение или карточки заболевания.',
  varietyCalendar: 'Календарь сорта',
  varietyStats: 'Статистика',
  disabledSoon: 'Скоро',
  queueTitle: 'Локальная очередь',
  queueOnline: 'Устройство в сети',
  queueOffline: 'Устройство офлайн',
  queueIntro:
    'Пока очередь используется как локальный lifecycle операций: создание сорта, сохранение карточек и смена статусов. Облачная отправка будет добавлена позже поверх этой модели.',
  queueEmptyTitle: 'Очередь пуста',
  queueEmptyBody: 'Все локальные операции завершены или еще не были созданы.',
  queueRetry: 'Повторить обработку',
  queueItemStatus: 'Статус',
  queueItemRetries: 'Повторов',
  queueItemError: 'Ошибка',
  creationNameLabel: 'Название сорта',
  creationNamePlaceholder: 'Например, Сорт 1 тест',
  creationDateLabel: 'Дата создания делянки',
  creationSowingLabel: 'Дата посева',
  creationDatePlaceholder: 'YYYY-MM-DD',
  creationLocationMissing: 'Точка еще не выбрана.',
  creationLocationButton: 'Определить местоположение',
  creationCurrentLocation: 'Текущая точка',
  creationConfirm: 'Подтверждаю',
  creationConfirmed: 'Подтверждено',
  creationPhotoMissing: 'Фотография делянки еще не сделана',
  creationTakePhoto: 'Сделать фото',
  creationRetakePhoto: 'Переснять фото',
  localReady: 'Готово локально',
  notStarted: taskStatusLabels.not_started,
  draft: taskStatusLabels.draft,
  queued: taskStatusLabels.queued,
  processed: taskStatusLabels.processed,
  varietyStatusReady: 'Создано в Google Sheets и Drive',
  varietyStatusSyncing: 'Идет отправка в Google',
  varietyStatusDraft: 'Черновик',
  varietyStatusErrorPrefix: 'Ошибка',
  unknownError: 'неизвестная ошибка',
  taskOverviewMissing: 'Обзорное фото не сделано',
  taskTakeOverview: 'Сделать обзорное фото',
  taskRetakeOverview: 'Переснять обзор',
  taskSourcePlotPhoto: 'Фото делянки из карточки сорта',
  taskSourcePlotPhotoMissing: 'Фото делянки еще не сохранено в сорте',
  taskSourceMap: 'Ссылка на координаты Google Maps',
  taskSourceMapMissing: 'Ссылка на карту еще не сохранена в сорте',
  taskOpenMap: 'Открыть точку на карте',
  taskCardsTitle: 'Карточки наблюдений',
  taskMeasurementHint:
    'Добавляйте карточки измерений: фото, значение и номер делянки.',
  taskObservationHint:
    'Добавьте локальную заготовку шага: обзорное фото и сохранение статуса.',
  taskCard: 'Карточка',
  taskCardPhotoMissing: 'Фото карточки отсутствует',
  taskTakeCardPhoto: 'Сделать фото карточки',
  taskRetakeCardPhoto: 'Переснять фото карточки',
  taskPlot: 'Делянка',
  taskPlotPlaceholder: '1, 2 или 3',
  taskRowNumber: 'Номер ряда',
  taskPlantNumber: 'Номер растения',
  taskDeleteCard: 'Удалить карточку',
  taskAddCard: 'Добавить карточку',
  taskAddInfection: 'Добавить заражение',
  taskCardReady: 'Карточка готова',
  taskCompleteCard: 'Готово',
  taskSaveCard: 'Сохранить карточку',
  taskSavedCard: 'Карточка сохранена',
  taskDraftCard: 'Черновик',
  taskQueuedCard: 'В очереди',
  taskSyncedCard: 'Записано локально',
  taskFailedCard: 'Ошибка локальной записи',
  taskSubmit: 'Отправить в очередь',
  taskQueuedDone: 'Данные поставлены в очередь на локальную обработку',
  taskExamplesTitle: 'Примеры карточек',
  taskExamplesBody:
    'Этот блок пока оставлен как локальный справочный placeholder для disease-экранов.',
  observationNote: 'Заметка',
  measurementValue: 'Значение',
  placeholderTaskTitle: 'Шаг требует уточнения',
  placeholderTaskBody:
    'Для этого признака в JSON пока нет явной внутренней разметки экрана. На этом этапе оставляем аккуратную локальную заготовку.',
  fusariumOverviewTitle: 'Карточки заболевания',
  fusariumCardsTitle: 'Карточки заболевания',
  fusariumOverviewHint: 'Первый обзорный экран больше не используется в пользовательском потоке.',
  fusariumCardsHint:
    'Осматривайте растения, добавляйте карточки заболевших растений и сохраняйте каждую карточку сразу после заполнения.',
  completeStep: 'Завершить шаг',
  goToCards: 'Перейти к карточкам заражений',
  placeholderContinue: 'Пока оставить как заготовку',
  stepNotFound: 'Шаг не найден',
  emptyClipboard: 'Буфер обмена пуст',
  invalidSheetsUrl: 'Ссылка в буфере не похожа на Google Sheets',
  importedVarietyFallback: 'Импортированный сорт',
  importedVarietyPrefix: 'Импортированный сорт',
  creationDraftMissing: 'Черновик создания сорта не найден',
  varietyNameRequired: 'Введите название сорта',
  taskOverviewRequired: 'Сначала добавьте обзорное фото',
  taskOverviewStepRequired: 'Сначала завершите обзор делянки',
  taskPlotPhotoRequired: 'Для каждой делянки нужны фото, геометка и подтверждение критерия',
  taskInfectionCardsRequired: 'Заполните все карточки заражений',
  taskMeasurementRequired: 'Для измерений нужны фото, значение и номер делянки',
  taskDiseasePhotoRequired: 'Для карточки заболевания нужно фото растения',
  taskDiseaseRowRequired: 'Для карточки заболевания нужен номер ряда',
  taskDiseasePlotRequired: 'Для карточки заболевания нужно указать делянку',
  taskDiseaseLocationRequired: 'Не удалось определить местоположение в момент съемки фото',
  taskPlaceholderRequired: 'Для локальной заготовки нужен хотя бы обзорный снимок',
  varietyNotFound: 'Сорт не найден',
  completeTaskBeforeQueue: 'Сначала локально завершите шаг',
  continueFailed: 'Не удалось продолжить',
  saveStepFailed: 'Не удалось сохранить шаг',
  completeStepFailed: 'Не удалось завершить шаг',
  localSyncError: 'Ошибка локальной обработки',
  unknownUser: 'пользователь не указан',
  noMap: 'карта не указана',
  returnToVariety: 'Вернуться к сорту',
} as const;

Object.assign(taskStatusLabels, {
  waiting_for_auth: 'Ожидает авторизацию',
  cloud_failed: 'Ошибка Google sync',
  locked_by_google: 'Заполнено в Google',
  analysis_invalid: 'Ошибка анализа',
});

Object.assign(v2Copy, {
  authCreateBody:
    'Для создания сорта приложение авторизуется в Google и получает доступ к созданию и редактированию файлов Drive и Sheets. После входа будет открыт мастер создания сорта.',
  authCreateAction: 'Авторизоваться в Google',
});

Object.assign(v2Copy, {
  startSubtitle: 'v2: локальные экраны и Google sync',
  googleDisabled: 'Google sync доступен после авторизации',
  queueIntro:
    'Очередь выполняет локальное применение, затем облачную запись в Google Sheets. Фото сначала загружаются в Google Drive, после этого URL записывается в таблицу.',
});
