import {
  ChoiceSheetKey,
  DiseaseSheetKey,
  LocalSheetKey,
  PhenologySheetKey,
  ScoreSheetKey,
  StructureSheetKey,
  ScreenMappingRule,
  TaskFlowKind,
  TaskKind,
} from '../types/app';
import { SHEET_ALIASES } from './templateSchema';

export interface CreationStepDefinition {
  id: string;
  screenId: string;
  title: string;
  type: ScreenMappingRule['type'];
  description: string;
  plot?: '1' | '2' | '3';
  options?: string[];
  field: string;
  sheet: string;
  header?: string;
}

export interface TaskDefinition {
  code: string;
  title: string;
  screenId: string;
  sheetName: string;
  logicalSheetKey?: LocalSheetKey;
  localSheetName?: string;
  futureRemoteSheetName?: string;
  kind: TaskKind;
  flowKind: TaskFlowKind;
  intro: string;
  criterionText?: string;
  options?: string[];
  scoreOptions?: string[];
  photoHint?: string;
  carouselAssetKey?: string;
  hasCarouselSamples?: boolean;
  overviewHint?: string;
  cardsHint?: string;
  observationLabel?: string;
  valueLabel?: string;
  valueUnit?: string;
  explicitlySpecified: boolean;
}

export const creationSteps: CreationStepDefinition[] = [
  {
    id: 'variety_name',
    screenId: 'screen_64e52250',
    title: 'Название сорта',
    type: 'text',
    description: 'Введите название сорта. Оно станет названием локальной записи сорта.',
    field: 'varietyName',
    sheet: 'делянки',
  },
  {
    id: 'dates',
    screenId: 'screen_73100733',
    title: 'Даты',
    type: 'date',
    description: 'Укажите дату создания делянки и дату посева.',
    field: 'dates',
    sheet: 'делянки',
  },
  {
    id: 'location',
    screenId: 'screen_3c6fdf96',
    title: 'Местоположение',
    type: 'location',
    description: 'Сохраните координаты делянок и ссылку на Google Maps для всех трех делянок.',
    field: 'location',
    sheet: 'делянки',
  },
  {
    id: 'plot1_area',
    screenId: 'screen_951193b7',
    title: 'Делянка 1: площадь',
    type: 'confirm',
    description: 'Подтвердите площадь делянки 1.',
    plot: '1',
    field: 'areaConfirmed',
    sheet: 'делянки',
    header: 'площадь делянки',
  },
  {
    id: 'plot1_row_spacing',
    screenId: 'screen_8caf316b',
    title: 'Делянка 1: расстояние междурядья',
    type: 'choice',
    description: 'Выберите расстояние междурядья.',
    plot: '1',
    options: ['15 см', '45 см', '70 см'],
    field: 'rowSpacing',
    sheet: 'делянки',
    header: 'расстояние междурядья',
  },
  {
    id: 'plot1_row_count',
    screenId: 'screen_86d0a45c',
    title: 'Делянка 1: количество рядков',
    type: 'choice',
    description: 'Выберите количество рядков.',
    plot: '1',
    options: ['4 рядка', '8 рядков', '10 рядков'],
    field: 'rowCount',
    sheet: 'делянки',
    header: 'количество рядков',
  },
  {
    id: 'plot1_plant_spacing',
    screenId: 'screen_781b733c',
    title: 'Делянка 1: расстояние между растениями',
    type: 'confirm',
    description: 'Подтвердите, что расстояние между растениями 8-10 см.',
    plot: '1',
    field: 'plantSpacingConfirmed',
    sheet: 'делянки',
    header: 'расстояние между растениями',
  },
  {
    id: 'plot1_photo',
    screenId: 'screen_0efa24b2',
    title: 'Делянка 1: фото',
    type: 'photo',
    description: 'Сделайте первое фото делянки 1.',
    plot: '1',
    field: 'photoUri',
    sheet: 'делянки',
    header: 'первое фото делянки',
  },
  {
    id: 'plot2_area',
    screenId: 'screen_580db949',
    title: 'Делянка 2: площадь',
    type: 'confirm',
    description: 'Подтвердите площадь делянки 2.',
    plot: '2',
    field: 'areaConfirmed',
    sheet: 'делянки',
    header: 'площадь делянки',
  },
  {
    id: 'plot2_row_spacing',
    screenId: 'screen_b4b9b986',
    title: 'Делянка 2: расстояние междурядья',
    type: 'choice',
    description: 'Выберите расстояние междурядья для делянки 2.',
    plot: '2',
    options: ['15 см', '45 см', '70 см'],
    field: 'rowSpacing',
    sheet: 'делянки',
    header: 'расстояние междурядья',
  },
  {
    id: 'plot2_row_count',
    screenId: 'screen_b9367a28',
    title: 'Делянка 2: количество рядков',
    type: 'choice',
    description: 'Выберите количество рядков для делянки 2.',
    plot: '2',
    options: ['4 рядка', '8 рядков', '10 рядков'],
    field: 'rowCount',
    sheet: 'делянки',
    header: 'количество рядков',
  },
  {
    id: 'plot2_plant_spacing',
    screenId: 'screen_08c5ed90',
    title: 'Делянка 2: расстояние между растениями',
    type: 'confirm',
    description: 'Подтвердите расстояние между растениями для делянки 2.',
    plot: '2',
    field: 'plantSpacingConfirmed',
    sheet: 'делянки',
    header: 'расстояние между растениями',
  },
  {
    id: 'plot2_photo',
    screenId: 'screen_1f45d2c6',
    title: 'Делянка 2: фото',
    type: 'photo',
    description: 'Сделайте первое фото делянки 2.',
    plot: '2',
    field: 'photoUri',
    sheet: 'делянки',
    header: 'первое фото делянки',
  },
  {
    id: 'plot3_area',
    screenId: 'screen_d558d573',
    title: 'Делянка 3: площадь',
    type: 'confirm',
    description: 'Подтвердите площадь делянки 3.',
    plot: '3',
    field: 'areaConfirmed',
    sheet: 'делянки',
    header: 'площадь делянки',
  },
  {
    id: 'plot3_row_spacing',
    screenId: 'screen_460e671b',
    title: 'Делянка 3: расстояние междурядья',
    type: 'choice',
    description: 'Выберите расстояние междурядья для делянки 3.',
    plot: '3',
    options: ['15 см', '45 см', '70 см'],
    field: 'rowSpacing',
    sheet: 'делянки',
    header: 'расстояние междурядья',
  },
  {
    id: 'plot3_row_count',
    screenId: 'screen_0e24676f',
    title: 'Делянка 3: количество рядков',
    type: 'choice',
    description: 'Выберите количество рядков для делянки 3.',
    plot: '3',
    options: ['4 рядка', '8 рядков', '10 рядков'],
    field: 'rowCount',
    sheet: 'делянки',
    header: 'количество рядков',
  },
  {
    id: 'plot3_plant_spacing',
    screenId: 'screen_5eeb03fb',
    title: 'Делянка 3: расстояние между растениями',
    type: 'confirm',
    description: 'Подтвердите расстояние между растениями для делянки 3.',
    plot: '3',
    field: 'plantSpacingConfirmed',
    sheet: 'делянки',
    header: 'расстояние между растениями',
  },
  {
    id: 'plot3_photo',
    screenId: 'screen_75b2fe72',
    title: 'Делянка 3: фото',
    type: 'photo',
    description: 'Сделайте первое фото делянки 3.',
    plot: '3',
    field: 'photoUri',
    sheet: 'делянки',
    header: 'первое фото делянки',
  },
];

function task(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  kind: TaskKind,
  flowKind: TaskFlowKind,
  intro: string,
  explicitlySpecified: boolean,
  extra?: Pick<
    TaskDefinition,
    'criterionText' | 'overviewHint' | 'cardsHint' | 'observationLabel' | 'valueLabel'
  >,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    kind,
    flowKind,
    intro,
    explicitlySpecified,
    ...extra,
  };
}

function diseaseTask(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  logicalSheetKey: DiseaseSheetKey,
  intro: string,
  cardsHint: string,
  explicitlySpecified: boolean,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    logicalSheetKey,
    localSheetName: SHEET_ALIASES[logicalSheetKey].local,
    futureRemoteSheetName: SHEET_ALIASES[logicalSheetKey].futureRemote,
    kind: 'infection',
    flowKind: 'disease_cards',
    intro,
    cardsHint,
    observationLabel: 'Описание заражения',
    explicitlySpecified,
  };
}

function phenologyTask(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  logicalSheetKey: PhenologySheetKey,
  intro: string,
  criterionText: string,
  explicitlySpecified: boolean,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    logicalSheetKey,
    localSheetName: SHEET_ALIASES[logicalSheetKey].local,
    futureRemoteSheetName: SHEET_ALIASES[logicalSheetKey].futureRemote,
    kind: 'observation',
    flowKind: 'phenology_by_plot',
    intro,
    criterionText,
    explicitlySpecified,
  };
}

function choiceTask(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  logicalSheetKey: ChoiceSheetKey,
  intro: string,
  photoHint: string,
  options: string[],
  explicitlySpecified: boolean,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    logicalSheetKey,
    localSheetName: SHEET_ALIASES[logicalSheetKey].local,
    futureRemoteSheetName: SHEET_ALIASES[logicalSheetKey].futureRemote,
    kind: 'observation',
    flowKind: 'choice_by_plot',
    intro,
    photoHint,
    options,
    explicitlySpecified,
  };
}

function scoreTask(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  logicalSheetKey: ScoreSheetKey,
  intro: string,
  photoHint: string,
  scoreOptions: string[],
  explicitlySpecified: boolean,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    logicalSheetKey,
    localSheetName: SHEET_ALIASES[logicalSheetKey].local,
    futureRemoteSheetName: SHEET_ALIASES[logicalSheetKey].futureRemote,
    kind: 'observation',
    flowKind: 'score_by_plot',
    intro,
    photoHint,
    scoreOptions,
    explicitlySpecified,
  };
}

function structureTask(
  code: string,
  title: string,
  screenId: string,
  sheetName: string,
  logicalSheetKey: StructureSheetKey,
  intro: string,
  photoHint: string,
  valueLabel: string,
  carouselAssetKey: string,
  explicitlySpecified: boolean,
  valueUnit?: string,
): TaskDefinition {
  return {
    code,
    title,
    screenId,
    sheetName,
    logicalSheetKey,
    localSheetName: SHEET_ALIASES[logicalSheetKey].local,
    futureRemoteSheetName: SHEET_ALIASES[logicalSheetKey].futureRemote,
    kind: 'measurement',
    flowKind: 'structure_by_sampling',
    intro,
    photoHint,
    valueLabel,
    valueUnit,
    carouselAssetKey,
    hasCarouselSamples: false,
    explicitlySpecified,
  };
}

const baseTaskDefinitions: TaskDefinition[] = [
  diseaseTask(
    '1',
    'Фузариоз',
    'screen_ee28f40a',
    '1.Фузариоз',
    'fusarium_sheet',
    'Сразу добавляйте карточки зараженных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения, сфотографируйте зараженное растение и укажите номер ряда, делянку и при необходимости номер растения.',
    true,
  ),
  diseaseTask(
    '2',
    'Септориоз',
    'screen_632cd366',
    '2.Септориоз',
    'septoria_sheet',
    'Сразу добавляйте карточки зараженных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с симптомами септориоза, сфотографируйте пораженное растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  diseaseTask(
    '3',
    'Повреждение блошкой',
    'screen_19db306a',
    '3.Повреждение блошкой',
    'flea_sheet',
    'Сразу добавляйте карточки поврежденных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с повреждением блошкой, сфотографируйте растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  phenologyTask(
    '4',
    'Начало цветения',
    'screen_63353f12',
    '4.Начало цветения',
    'start_flowering_sheet',
    'Зафиксируйте начало цветения по всем трем делянкам. Для каждой делянки нужен снимок и подтверждение критерия шага.',
    'Зацвело 10% растений на делянке',
    true,
  ),
  phenologyTask(
    '5',
    'Полное цветение',
    'screen_67aec0ea',
    '5.Полное цветение',
    'full_flowering_sheet',
    'Зафиксируйте полное цветение по всем трем делянкам. Для каждой делянки нужен снимок и подтверждение критерия шага.',
    'Зацвело не менее 50% растений в средней части центральных побегов',
    true,
  ),
  diseaseTask(
    '6',
    'Бактериоз',
    'screen_46b45849',
    '6.Бактериоз',
    'bacteriosis_sheet',
    'Сразу добавляйте карточки зараженных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с симптомами бактериоза, сфотографируйте пораженное растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  diseaseTask(
    '7',
    'Пероноспороз',
    'screen_846d4d30',
    '7.Пероноспороз',
    'peronosporosis_sheet',
    'Сразу добавляйте карточки зараженных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с симптомами пероноспороза, сфотографируйте пораженное растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  diseaseTask(
    '8',
    'Церкоспороз',
    'screen_a3087365',
    '8.Церкоспороз',
    'cercosporosis_sheet',
    'Сразу добавляйте карточки зараженных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с симптомами церкоспороза, сфотографируйте пораженное растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  diseaseTask(
    '9',
    'Повреждение тлей',
    'screen_d55cfdda',
    '9.Повреждение тлей',
    'aphid_damage_sheet',
    'Сразу добавляйте карточки поврежденных растений по делянкам 1, 2 или 3.',
    'Тщательно осмотрите растения с повреждением тлей, сфотографируйте растение и укажите номер ряда, делянку и при необходимости номер растения.',
    false,
  ),
  task(
    '10',
    'Цветок: окраска',
    'screen_774494b0',
    '10.Цветок окраска',
    'observation',
    'placeholder_pending_spec',
    'Для этого признака пока нет явной структуры экрана в JSON.',
    false,
  ),
  phenologyTask(
    '11',
    'Конец цветения',
    'screen_705e57e3',
    '11.Конец цветения',
    'end_flowering_sheet',
    'Зафиксируйте конец цветения по всем трем делянкам. Для каждой делянки нужен снимок и подтверждение критерия шага.',
    'Цветки на верхнем ярусе засыхают',
    true,
  ),
  task(
    '12',
    'Лист: форма бокового листочка',
    'screen_051e965f',
    '12.Лист форма бокового листочка',
    'observation',
    'placeholder_pending_spec',
    'Для этого признака пока нет явной структуры экрана в JSON.',
    false,
  ),
  phenologyTask(
    '13',
    'Полное созревание',
    'screen_3ca89211',
    '13.Полное созревание',
    'full_maturity_sheet',
    'Зафиксируйте полное созревание по всем трем делянкам. Для каждой делянки нужен снимок и подтверждение критерия шага.',
    'Созрело 50% бобов на делянке',
    true,
  ),
  task(
    '14',
    'Растение: окраска опушения главного стебля',
    'screen_ae5f827b',
    '14.Растение окраска опушения главного стебля',
    'observation',
    'placeholder_pending_spec',
    'Для этого признака пока нет явной структуры экрана в JSON.',
    false,
  ),
  task(
    '15',
    'Устойчивость к полеганию',
    'screen_14689efc',
    '15.Устойчивость к полеганию',
    'observation',
    'placeholder_pending_spec',
    'Для этого признака пока нет явной структуры экрана в JSON.',
    false,
  ),
  task(
    '16',
    'Устойчивость к осыпанию',
    'screen_d118e3c9',
    '16.Устойчивость к осыпанию',
    'observation',
    'placeholder_pending_spec',
    'Для этого признака пока нет явной структуры экрана в JSON.',
    false,
  ),
  task(
    '17',
    'Длина стебля',
    'screen_dd7351b2',
    '17.Длина стебля',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений длины стебля по растениям.',
    false,
    { valueLabel: 'Длина стебля, см' },
  ),
  task(
    '18',
    'Высота прикрепления нижнего боба',
    'screen_d6898e2e',
    '18.Высота прикрепления нижнего боба',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Высота, см' },
  ),
  task(
    '19',
    'Количество продуктивных узлов на главном стебле',
    'screen_20cf2da6',
    '19.Количество продуктивных узлов на главном стебле',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество узлов' },
  ),
  task(
    '20',
    'Количество ветвей',
    'screen_7b7bc1ec',
    '20.Количество ветвей',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество ветвей' },
  ),
  task(
    '21',
    'Количество продуктивных бобов',
    'screen_88f856ba',
    '21.Количество продуктивных бобов',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество бобов' },
  ),
  task(
    '22',
    'Количество бобов на продуктивный узел',
    'screen_04fe9e12',
    '22.Количество бобов на продуктивный узел',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество бобов' },
  ),
  task(
    '23',
    'Количество семян с растения',
    'screen_d37e56e7',
    '23.Количество семян с растения',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество семян' },
  ),
  task(
    '24',
    'Количество семян в бобе',
    'screen_2addcc5e',
    '24.Количество семян в бобе',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Количество семян' },
  ),
  task(
    '25',
    'Масса семян с растения',
    'screen_3d8873a9',
    '25.Масса семян с растения',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Масса, г' },
  ),
  task(
    '26',
    'Урожайность с единицы площади',
    'screen_d36d4541',
    '26.Урожайность с единицы площади',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Урожайность' },
  ),
  task(
    '27',
    'Масса 1000 семян',
    'screen_1a5ef412',
    '27.Масса 1000 семян',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Масса, г' },
  ),
  task(
    '28',
    'Содержание белка',
    'screen_f27a2c47',
    '28.Содержание белка',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Содержание, %' },
  ),
  task(
    '29',
    'Содержание жира',
    'screen_c147d338',
    '29.Содержание жира',
    'measurement',
    'measurement_cards',
    'Добавляйте карточки измерений по растениям.',
    false,
    { valueLabel: 'Содержание, %' },
  ),
];

export const taskDefinitions: TaskDefinition[] = [
  ...baseTaskDefinitions.filter(
    (item) =>
      ![
        '10',
        '12',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
      ].includes(item.code),
  ),
  choiceTask(
    '10',
    'Цветок: окраска',
    'screen_774494b0',
    '10.Цветок: окраска',
    'flower_color_sheet',
    'Зафиксируйте окраску цветка по всем трем делянкам. Для каждой делянки нужно фото признака и один вариант из справочника.',
    'Сделайте фото цветка крупным планом.',
    ['Белая', 'Фиолетовая'],
    true,
  ),
  choiceTask(
    '12',
    'Лист: форма бокового листочка',
    'screen_051e965f',
    '12.Лист: форма бокового листочка',
    'leaf_shape_sheet',
    'Зафиксируйте форму бокового листочка по всем трем делянкам. Для каждой делянки нужно фото признака и один вариант из справочника.',
    'Сделайте фото бокового листочка крупным планом.',
    ['Ланцетовидная', 'Треугольная', 'Заостренно-яйцевидная', 'Округло-яйцевидная'],
    true,
  ),
  choiceTask(
    '14',
    'Растение: окраска опушения главного стебля',
    'screen_ae5f827b',
    '14.Растение: окраска опушения главного стебля',
    'stem_pubescence_color_sheet',
    'Зафиксируйте окраску опушения главного стебля по всем трем делянкам. Для каждой делянки нужно фото признака и один вариант из справочника.',
    'Сделайте фото опушения главного стебля крупным планом.',
    ['Серая', 'Рыжая'],
    true,
  ),
  scoreTask(
    '15',
    'Устойчивость к полеганию',
    'screen_14689efc',
    '15.Устойчивость к полеганию',
    'lodging_resistance_sheet',
    'Оцените устойчивость к полеганию по всем трем делянкам. Для каждой делянки нужен снимок общего состояния и один балл по шкале.',
    'Сделайте фото делянки целиком так, чтобы было видно степень полегания.',
    ['1', '3', '5', '7', '9'],
    true,
  ),
  scoreTask(
    '16',
    'Устойчивость к осыпанию',
    'screen_d118e3c9',
    '16.Устойчивость к осыпанию',
    'shattering_resistance_sheet',
    'Оцените устойчивость к осыпанию по всем трем делянкам. Для каждой делянки нужен снимок общего состояния и один балл по шкале.',
    'Сделайте фото делянки целиком так, чтобы было видно состояние растений перед оценкой осыпания.',
    ['1', '3', '5', '7', '9'],
    true,
  ),
  structureTask(
    '17',
    'Длина стебля',
    'screen_8f702b12',
    '17.Длина стебля',
    'stem_length_sheet',
    'Для каждой из двух выборок выберите делянку, затем добавьте карточки растений с фото, номером растения и измеренным значением длины стебля.',
    'Сделайте фото растения целиком так, чтобы был виден измеряемый стебель.',
    'Длина стебля, см',
    'stem_length',
    true,
    'см',
  ),
  structureTask(
    '18',
    'Высота прикрепления нижнего боба',
    'screen_4f5a16ee',
    '18.Высота прикрепления нижнего боба',
    'lower_pod_attachment_sheet',
    'Для каждой из двух выборок выберите делянку, затем добавьте карточки растений с фото, номером растения и измеренным значением высоты прикрепления нижнего боба.',
    'Сделайте фото растения так, чтобы был виден нижний боб и место его прикрепления.',
    'Высота прикрепления нижнего боба, см',
    'lower_pod_attachment_height',
    true,
    'см',
  ),
  structureTask(
    '19',
    'Количество продуктивных узлов на главном стебле',
    'screen_2dcf3f6d',
    '19.Количество продуктивных узлов на главном стебле',
    'productive_nodes_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и количеством продуктивных узлов.',
    'Сделайте фото растения так, чтобы был виден главный стебель и узлы.',
    'Количество продуктивных узлов',
    'productive_nodes_count',
    true,
  ),
  structureTask(
    '20',
    'Количество ветвей',
    'screen_68c0c0d8',
    '20.Количество ветвей',
    'branch_count_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и количеством ветвей.',
    'Сделайте фото растения так, чтобы были различимы ветви.',
    'Количество ветвей',
    'branch_count',
    true,
  ),
  structureTask(
    '21',
    'Количество продуктивных бобов',
    'screen_d4f46f32',
    '21.Количество продуктивных бобов',
    'productive_pods_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и количеством продуктивных бобов.',
    'Сделайте фото растения так, чтобы были видны продуктивные бобы.',
    'Количество продуктивных бобов',
    'productive_pods_count',
    true,
  ),
  structureTask(
    '22',
    'Количество бобов на продуктивный узел',
    'screen_3505c2dc',
    '22.Количество бобов на продуктивный узел',
    'pods_per_node_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и расчетным значением количества бобов на продуктивный узел.',
    'Сделайте фото растения или его части так, чтобы можно было соотнести расчет с конкретным растением.',
    'Количество бобов на продуктивный узел',
    'pods_per_productive_node',
    true,
  ),
  structureTask(
    '23',
    'Количество семян с растения',
    'screen_ec5fd43b',
    '23.Количество семян с растения',
    'seeds_per_plant_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и количеством семян с растения.',
    'Сделайте фото растения или собранной пробы, связанной с конкретным растением.',
    'Количество семян с растения',
    'seeds_per_plant',
    true,
  ),
  structureTask(
    '24',
    'Количество семян в бобе',
    'screen_1e4689f4',
    '24.Количество семян в бобе',
    'seeds_per_pod_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и расчетным значением количества семян в бобе.',
    'Сделайте фото боба или связанного образца так, чтобы было понятно, к какому растению относится запись.',
    'Количество семян в бобе',
    'seeds_per_pod',
    true,
  ),
  structureTask(
    '25',
    'Масса семян с растения',
    'screen_03044749',
    '25.Масса семян с растения',
    'seed_weight_per_plant_sheet',
    'Для каждой из двух выборок выберите делянку и добавьте карточки растений с фото, номером растения и массой семян с растения.',
    'Сделайте фото растения или связанной пробы семян перед внесением массы.',
    'Масса семян с растения, г',
    'seed_weight_per_plant',
    true,
    'г',
  ),
].map((item) =>
  ['10', '12', '14', '15', '16'].includes(item.code)
    ? {
        ...item,
        carouselAssetKey:
          item.code === '10'
            ? 'flower_color'
            : item.code === '12'
              ? 'lateral_leaf_shape'
              : item.code === '14'
                ? 'stem_pubescence_color'
                : item.code === '15'
                  ? 'lodging_resistance'
                  : 'shattering_resistance',
        hasCarouselSamples: false,
      }
    : item,
);

export const taskDefinitionsByCode = Object.fromEntries(
  taskDefinitions.map((item) => [item.code, item]),
) as Record<string, TaskDefinition>;

export const screenRules: ScreenMappingRule[] = creationSteps.map((step) => ({
  screenId: step.screenId,
  title: step.title,
  type: step.type,
  sheet: step.sheet,
  field: step.field,
  plot: step.plot,
}));
