export type V2RootStackParamList = {
  Start: undefined;
  Auth: { mode: 'link' | 'create' | 'resumeCreation'; force?: boolean };
  Catalog: undefined;
  Creation: undefined;
  CreationCloudSync: undefined;
  Variety: { varietyId: string };
  FusariumCards: { varietyId: string; taskCode: string };
  ChoiceTask: { varietyId: string; taskCode: string };
  ScoreTask: { varietyId: string; taskCode: string };
  YieldTask: { varietyId: string; taskCode: string };
  ThousandSeedWeightTask: { varietyId: string; taskCode: string };
  ProteinContentTask: { varietyId: string; taskCode: string };
  FatContentTask: { varietyId: string; taskCode: string };
  PhenologyTask: { varietyId: string; taskCode: string };
  StructureSamplingTask: { varietyId: string; taskCode: string };
  ObservationTask: { varietyId: string; taskCode: string };
  MeasurementTask: { varietyId: string; taskCode: string };
  PendingTask: { varietyId: string; taskCode: string };
  Queue: undefined;
};
